name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # メインブランチへのプッシュ時にも実行

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    environment: github-pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # 使用するNode.jsのバージョン

    - name: Setup pnpm
      run: |
        npm install -g pnpm
  
    - name: Install dependencies
      run: pnpm install

    - name: Fetch data
      env:
        MY_GITHUB_TOKEN: ${{ secrets.FETCH_DATA_TOKEN }}
      run: pnpm run fetchData

    - name: Build project
      run: pnpm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}} 
        publish_dir: ./dist # 出力ディレクトリを指定
